### ISSUE TITLE
Ability to sort icons in the collection by name.

### ISSUE THREAD

**Issue by MrRobz** [Icon-Shelf/icon-shelf#103]
Ascending/descending/none

Can be another option in collection menu. On each click of menu item the sort changes.
<img width="338" alt="image" src="https://user-images.githubusercontent.com/21201812/193346877-95f7f069-6d1a-48fd-804d-5d8d1c50fda6.png">

**Comment by ranjandsingh** [comment]
Hey @MrRobz  I would like to help on this one

**Comment by Shaglock** [comment]
Hello @MrRobz, I tried to implement this as part of hacktoberfest, could you please take a look at PR that I opened? https://github.com/Icon-Shelf/icon-shelf/pull/142
