### ISSUE TITLE
Add tooltip text to hide and edit action buttons

### ISSUE THREAD

**Issue by MrRobz** [Icon-Shelf/icon-shelf#106]
In the customize modal for the colection, add toll tips for the hide eye and edit icon buttons.

Tooltip info:
```
eye icon - text: "Show/Hide" - placement: right
edit icon - text: "Edit" - placement top
```

<img width="192" alt="image" src="https://user-images.githubusercontent.com/21201812/193420524-eb886121-9344-4414-a92c-36eadc3584a3.png">

<img width="670" alt="image" src="https://user-images.githubusercontent.com/21201812/193420531-fb8d8ed3-e1fa-4a9f-8b05-5b7908f551f4.png">

<img width="363" alt="image" src="https://user-images.githubusercontent.com/21201812/193420545-1a165959-07ca-4475-9ba7-583afc7ed390.png">

Use the existing `<Tooltip` component

**Comment by jkol7** [comment]
I would like to try this one please. @MrRobz

**Comment by MrRobz** [comment]
> I would like to try this one please. @MrRobz

Go for it

**Comment by jayeshchoudhary** [comment]
This can be closed
