### ISSUE TITLE
Upgrade some packages related to styling

### ISSUE THREAD

**Issue by MrRobz** [Icon-Shelf/icon-shelf#108]
Task is to upgrade these packages to the latest version in package.json

```
@fontsource/dm-sans                  ^4.5.7  →     ^4.5.8
@headlessui/react                    ^1.6.6  →     ^1.7.3
autoprefixer                        ^10.4.7  →   ^10.4.12
postcss                             ^8.4.14  →    ^8.4.17
rc-tooltip                           ^5.2.1  →     ^5.2.2
 react-inlinesvg                      ^3.0.0  →     ^3.0.1
tailwindcss                          ^3.1.6  →     ^3.1.8
```

Things to verify after upgrading and running `npm run watch`
* dm-sans font is loaded correctly
* headless/react components used are working correctly - menu, dropdown, button
* tooltip shown correctly
* SVGs shown correctly both in light and dark mode
* No breakage in styling of the app

<img width="313" alt="image" src="https://user-images.githubusercontent.com/21201812/193421229-edcb6730-09f3-4f05-8a59-a0c3a42902f6.png">

**Comment by parulgupta26** [comment]
Hey @MrRobz  I can take this up. Please assign to me.

**Comment by parulgupta26** [comment]
@MrRobz  Kindly review the PR - https://github.com/Icon-Shelf/icon-shelf/pull/110

**Comment by parulgupta26** [comment]
Hi @MrRobz  Since the PR is merged, you might want to close this issue :)
