### ISSUE TITLE
The search icon in search bar not vertically centre aligned 

### ISSUE THREAD

**Issue by MrRobz** [Icon-Shelf/icon-shelf#113]
<img width="273" alt="image" src="https://user-images.githubusercontent.com/21201812/193422629-08693123-caf3-41a4-82ec-15db2879e358.png">

<img width="77" alt="image" src="https://user-images.githubusercontent.com/21201812/193422637-d72dda52-1e3f-4019-b507-eec1084ce28c.png">

<img width="1554" alt="Screenshot 2022-10-01 at 11 43 24 PM" src="https://user-images.githubusercontent.com/21201812/193422673-74b2a2f3-be2f-4955-bd4a-9ae115488709.png">

The icons seem to be bit lower that the center

**Comment by parulgupta26** [comment]
Hi @MrRobz  I can fix this. Please assign to me.
