### ISSUE TITLE
Migrate from "react-query" package to @tanstack/react-query package

### ISSUE THREAD

**Issue by MrRobz** [Icon-Shelf/icon-shelf#119]
follow this doc for the migration
https://tanstack.com/query/v4/docs/guides/migrating-to-react-query-4

**Comment by Hackerbone** [comment]
Hey @MrRobz I'd like to work on this! I've worked with react-query, would love to understand tanstack's react-query.

**Comment by Hackerbone** [comment]
Also I would want to update the Contribution file. Add an `npm install` command and specify the required node version to work with so that there are not dependency inconsistencies! Can I create an issue for this?

**Comment by MrRobz** [comment]
> Also I would want to update the Contribution file. Add an `npm install` command and specify the required node version to work with so that there are not dependency inconsistencies! Can I create an issue for this?

Yes pls
