### ISSUE TITLE
Upgrade github action steps

### ISSUE THREAD

**Issue by MrRobz** [Icon-Shelf/icon-shelf#122]
For the github actions workflows present, upgrade these steps to v3
```
actions/checkout@v2 -> actions/checkout@v3
actions/setup-node@v2 -> actions/setup-node@v3
actions/cache@v2 -> actions/cache@v2
```

and migrations that needs to be done.
This needs to be done for these action files

<img width="393" alt="image" src="https://user-images.githubusercontent.com/21201812/193468716-f56c6afc-6b7b-4c47-86fc-2d1092dab559.png">

**Comment by parulgupta26** [comment]
@MrRobz  I can help with this :)

**Comment by parulgupta26** [comment]
@MrRobz Please review PR #123

**Comment by parulgupta26** [comment]
@MrRobz reminder to close this issue ;)
