### ISSUE TITLE
Update CONTRIBUTION.md with some extra steps for setting up environment

### ISSUE THREAD

**Issue by Hackerbone** [Icon-Shelf/icon-shelf#124]
**Is your feature request related to a problem? Please describe.**
There are some steps that are required to be done to fully setup dev environment for this project

**Describe the solution you'd like**
Add `npm install` as a command and specify node versions we're working with

@MrRobz please assign this issue to me, i'll start working on this!

**Comment by Hackerbone** [comment]
Wanted to ask what is the node version we're working with? Also do add the `hacktoberfest` label to this issue! Thanks :smile:

**Comment by MrRobz** [comment]
> Wanted to ask what is the node version we're working with? Also do add the `hacktoberfest` label to this issue! Thanks 😄

node 16
