### ISSUE TITLE
Choose the default "Copy" behavior

### ISSUE THREAD

**Issue by juliennicouleaud** [Icon-Shelf/icon-shelf#143]
Hi! It would be nice to be able to choose the default CMD+C or CTRL+C behavior -> I'm a not a developer, thus the "Copy as REACT" is not very useful to me, I'd rather "Copy as SVG" be the default for my usage.

**Comment by MrRobz** [comment]
That is totally customisable, all you have to do is click on customize action for the collection and move copy as SVG to the top and save.

<img width="260" alt="image" src="https://user-images.githubusercontent.com/21201812/200632739-e6764211-651b-4728-9a66-6cdf5d89a82c.png">

<img width="401" alt="image" src="https://user-images.githubusercontent.com/21201812/200632779-b9a44ea6-3853-41db-a07a-5901d3b12e10.png">

https://icon-shelf.github.io/faqs/customize-copy-action/

**Comment by juliennicouleaud** [comment]
Great, thanks!
