### ISSUE TITLE
Ability to select a default 'copy' type

### ISSUE THREAD

**Issue by cheerlessDreamer** [Icon-Shelf/icon-shelf#146]
Currently the default copy type is React, but I personally don't use React ever. It would be handy if I were able to choose the default copy mode instead of always clicking the meatball button each time.

**Comment by MrRobz** [comment]
Click on customize action menu and move the action you want as the default to the top.

<img width="319" alt="image" src="https://user-images.githubusercontent.com/21201812/217502384-a4c179ab-97ac-4b78-8f5e-7e8d471d9bd3.png">

<img width="430" alt="image" src="https://user-images.githubusercontent.com/21201812/217502439-14cba35f-6372-4771-a618-d02e7971e453.png">
