### ISSUE TITLE
Scrollbar Design on Homepage

### ISSUE THREAD

**Issue by poypoydev** [Icon-Shelf/icon-shelf#151]
**Is your feature request related to a problem? Please describe.**
Not related to a "problem", I just did not like the default scrollbar look on the homepage.

**Describe the solution you'd like**
I would like a custom scrollbar on the homepage.

**Describe alternatives you've considered**
I forked the project to implement a custom scrollbar, I will leave a short video down below. 

**Additional context**
Video of the scrollbar I implemented.  

https://user-images.githubusercontent.com/97455492/233783400-13827699-b41b-4778-9907-6cbc3221ce6d.mp4

**Comment by MrRobz** [comment]
Wow looks really nice. Would love to have a look at your pull request

**Comment by poypoydev** [comment]
Alright, just made one 👍
