### ISSUE TITLE
Add cmd/control + c shortcut for icon

### ISSUE THREAD

**Issue by MrRobz** [Icon-Shelf/icon-shelf#19]
While an icon is selected, pressing `cmd/control + c` should invoke the first collection action.

use react-hotkeys package for this.

**Comment by dteo318** [comment]
Hi! Could I give this a shot?

**Comment by MrRobz** [comment]
Could be due to having a subMenu item with the shortcut.
@dteo318 can you try going to `src/menu.ts` and removing subMenuEdit items.

I would very much like if we can implement `ctrl/cmd + C shortcut` instead of `ctrl + L` as its more intuitive.

**Comment by dteo318** [comment]
That solved it! I commented out the Electron `ctrl/cmd + C shortcut` and used `ctrl/cmd + C` as the shortcut for the first collection action. Will make a pull request!
