### ISSUE TITLE
Add a secondary menu button and show rest of the collection actions

### ISSUE THREAD

**Issue by MrRobz** [Icon-Shelf/icon-shelf#63]
On right click of an icon we show a list of collection actions.
<img width="305" alt="image" src="https://user-images.githubusercontent.com/21201812/193340763-ec8448c1-b561-4788-88c8-6a14ec331752.png">

Need to show these actions on the right pane as well as secondary actions.
<img width="442" alt="image" src="https://user-images.githubusercontent.com/21201812/193340833-49f3fa3d-0d49-478e-85ca-1634003617f9.png">

What I'm looking for is something like primary button and a menu secondary button on its right.
Something like 

<img width="179" alt="image" src="https://user-images.githubusercontent.com/21201812/193340959-e041aa8c-f241-49ff-bee9-38e1fc386786.png">

<img width="212" alt="image" src="https://user-images.githubusercontent.com/21201812/193340988-aa81a91f-82e0-494a-803f-6a87b5887e11.png">
 
Don't want any new libraries to be added, but try to use https://headlessui.com/react/menu and build a custom component.

**Comment by fazzaamiarso** [comment]
Hi, @MrRobz can I help you with this?

**Comment by fazzaamiarso** [comment]
@MrRobz If I understand correctly, you want a custom button with secondary button that open a customizable dropdown  right?

Do I just create the custom component or implement it too somewhere?

**Comment by MrRobz** [comment]
<img width="221" alt="image" src="https://user-images.githubusercontent.com/21201812/193506757-6c43ca08-cdee-4c83-8333-a20745040260.png">

<img width="435" alt="image" src="https://user-images.githubusercontent.com/21201812/193506773-a3c133bf-9e51-4703-bf01-7959bcc716a5.png">

This is what I'm looking for @fazzaamiarso.
There will a secondary button beside the button on click opens menu with the collection actions.

The menu will have the same options as when you right-click an icon
<img width="340" alt="image" src="https://user-images.githubusercontent.com/21201812/193506923-a4f6be11-7dfc-4895-a39f-0afc8bb13e93.png">

This could be a new component in `src/components/ui/atomic-components` we can call it DropdownButton
