### ISSUE TITLE
Primary action button not refreshing after re-ordering actions

### ISSUE THREAD

**Issue by MrRobz** [Icon-Shelf/icon-shelf#69]
The first action in customize action becomes the primary action for the collection. But after re-ordering and moving action to first item the primary button does not change. But doing a page reload makes it change.

The primary action should update as soon as clicking on "done and save" button.

https://drive.google.com/file/d/1Vb6dk_90y0iREOMrE1tLd7PPuqCHRBs_/view?usp=sharing

<img width="313" alt="image" src="https://user-images.githubusercontent.com/21201812/193339694-af5583a4-8ca0-46d0-ae47-971fb783a9ce.png">

**Comment by ageddesi** [comment]
Will take a quick look and see if this is something I can help with.

**Comment by parulgupta26** [comment]
@MrRobz  I can work on this. Please assign to me.

**Comment by parulgupta26** [comment]
@MrRobz Kindly assign this to me so I can work on the fix.

**Comment by parulgupta26** [comment]
@MrRobz  Please review the PR #117

**Comment by parulgupta26** [comment]
@MrRobz reminder to close this issue ;)
