### ISSUE TITLE
Cannot import icons more than 10 into selected icon category each time

### ISSUE THREAD

**Issue by youhengchan** [Icon-Shelf/icon-shelf#70]
**Describe the bug**
I tried to import Google's material design svg icons (7000+ files) into a already exsisted category, But it does not work.
The walk around is to import the whole folder at the time that you create an icon set and specify 
the icon dataset folder before the category get initialized.
  
**To Reproduce**

1. Go to main window and select any item under **collections**
2. Click **+ Add icon** in the main window or if the collection is empty, you can also click the "Click here to add icons to collection" to open the dialog window to select icons to add.
3. Click blue **Add** button and selected 7000 thousand svg files from the file browser.
4. Stuck since then

**Expected behavior**
All the files could be added to the selected category properly

**Screenshots**
<img width="836" alt="iShot2022-02-06 00 38 24" src="https://user-images.githubusercontent.com/44702487/152650452-8d6d66c3-edb5-468f-ae8d-41f4e7973c23.png">

**Additional context**
The walk around is to create a new category and import the huge dataset before the collection category get created.
It might hlep at this moment.

**Comment by MrRobz** [comment]
addressed in https://github.com/Icon-Shelf/icon-shelf/pull/80

**Comment by youhengchan** [comment]
您的邮件，已经正确投递至youheng。
