### ISSUE TITLE
A way to submit bugs or feedback from the app

### ISSUE THREAD

**Issue by ab-dt** [Icon-Shelf/icon-shelf#73]
**Is your feature request related to a problem? Please describe.**
When user faces an issue with something in the app, there is no human to reach out to directly or write about it in place.

**Describe the solution you'd like**
Either the solution could be is to add a link to Github issues and file a bug or add an inplace feedback form for users to submit it directly. Feedback could also be displayed inside iconshelf website and bugs could be created automatically on Github issues itself.
Could also be a place for users to submit their rating.
And also add a Star icon for users to star the Github codebase.

**Comment by MrRobz** [comment]
For feedback and bugs reporting you can click on the loudspeaker icon on the bottom left. It should open up a modal where you would see an "add an idea" button. Use that form to write your idea.

Ideas can be feedback, bugs, integrations etc.

<img width="203" alt="image" src="https://user-images.githubusercontent.com/21201812/153348813-e79b4b8d-4b44-43f9-8855-4029ac3e7e13.png">

<img width="199" alt="image" src="https://user-images.githubusercontent.com/21201812/153349047-f165ea12-e3db-41cb-bfdd-cf9e06375ec5.png">

<img width="456" alt="image" src="https://user-images.githubusercontent.com/21201812/153349170-214faf43-aefa-40b5-9e35-5540ea0612d6.png">
