### ISSUE TITLE
Make left nav's width adjustable

### ISSUE THREAD

**Issue by MrRobz** [Icon-Shelf/icon-shelf#75]
Today the left nav pane width is fixed, would be nice if this pane could be re-sizable.

<img width="361" alt="image" src="https://user-images.githubusercontent.com/21201812/193342091-b7fac8e6-7707-430e-92f1-66eaf6065657.png">

https://github.com/bokuweb/re-resizable might be able to do the job.
https://bokuweb.github.io/re-resizable/?path=/story/auto--width

**Comment by prasoonmhwr** [comment]
please assign it to me :)

**Comment by prasoonmhwr** [comment]
@MrRobz what should be the max-width of nav.

**Comment by MrRobz** [comment]
> @MrRobz what should be the min-width and max-width of nav.

min-width: 16rem;
max-width: 48rem;

**Comment by prasoonmhwr** [comment]
@MrRobz Have created a PR , please check :)

**Comment by MrRobz** [comment]
Closed 
https://github.com/Icon-Shelf/icon-shelf/pull/118
