### ISSUE TITLE
Zondicons no preview

### ISSUE THREAD

**Issue by PlkMarudny** [Icon-Shelf/icon-shelf#81]
**Describe the bug**
[Zondicons](https://www.zondicons.com/icons.html) are not enerated

**To Reproduce**

1. Go to https://www.zondicons.com/icons.html
2. Download icons, unzip the archive
3. Add to Icon Shelf
4. No preview generates

**Expected behavior**
Guess preview of each icon should be displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/4361591/158809071-7cee7afb-b0cc-4516-851e-c8897e04ad2c.png)

**Comment by MrRobz** [comment]
Thank you for reporting this. I'll check it out.

**Comment by MrRobz** [comment]
I've fixed this, please download the latest version from https://github.com/Icon-Shelf/icon-shelf/releases and try.
