### ISSUE TITLE
Consider a portable version for Windows?

### ISSUE THREAD

**Issue by tomasts248** [Icon-Shelf/icon-shelf#87]
Hi, perhaps to consider making a portable package download for Windows? Which pretty much means that all the settings should be stored inside the app folder as opposed to inside the windows registry, using relative paths so that I can carry the collection of icons as a relative path between computers.
Also as an advice if in the future your decide to make a portable version you can publish it here for increased visibility in portableapps.com and even get help there for portabilizing it. In fact there's no portable software in this niche yet..
Kind regards.

**Comment by MrRobz** [comment]
Thanks for the advice @tomasts248. But I don't have any plans as of now to port icon-shelf to a windows portable version.

**Comment by tomasts248** [comment]
Oh alright :(
