### ISSUE TITLE
I can't scroll on the collections panel

### ISSUE THREAD

**Issue by orar** [Icon-Shelf/icon-shelf#93]
OS: Ubuntu 20.04
Version: 0.1.13 / AppImage

I downloaded it a couple of weeks ago and began out recently.

I have added about 10 collections and when it overflew the panel height, I can't scroll down to access other collections.

I don't know if it's a bug or if my system is the cause.

**Comment by MrRobz** [comment]
Could be a bug, would you be kind enough to upload a screenshot here.
